<testsuite errors="1" failures="0" hostname="HIBACL64245" name="login.login" skipped="0" tests="1" time="65.71733" timestamp="2019-04-04T19:39:44.725606"><testcase classname="login.login" name="login" status="failed" time="65.71733"><error message="Message: no such element: Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;//span[contains(text(),'CUSTOMER MANAGEMENT')]&quot;}&#10;  (Session info: chrome=73.0.3683.86)&#10;  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.16299 x86_64)&#10;" type="NoSuchElementException">
<![CDATA[
Failing step: When I login to the application ... failed in 60.255s
Location: features/login.feature:8
Traceback (most recent call last):
  File "c:\users\schettiar\appdata\local\programs\python\python37-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "c:\users\schettiar\appdata\local\programs\python\python37-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features\steps\login_steps.py", line 31, in step_impl
    home_page.click_customer_management_tab()
  File "C:\Users\schettiar\PycharmProjects\python_bdd_selenium\pages\home_page.py", line 16, in click_customer_management_tab
    self.driver.find_element_by_xpath(self.customer_management_tab).click()
  File "c:\users\schettiar\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "c:\users\schettiar\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "c:\users\schettiar\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\schettiar\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),'CUSTOMER MANAGEMENT')]"}
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.16299 x86_64)

]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @GLSWW-1603
  Scenario: login
    Given I navigate to the URL ... passed in 5.462s
    When I login to the application ... failed in 60.255s
    Then the application should enter accounts page ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>